name: Amp Buildkite Plugin
description: Run Amp on Buildkite
author: https://github.com/sj26
requirements:
  - bash
configuration:
  properties:
    prompt:
      type: string
  required:
    - prompt
  additionalProperties: false
